### ISSUE TITLE
Don't Compile Files with Underscore Prefix

### ISSUE THREAD

**Issue by realph** [Shopify/shopify-css-import#16]
Is it possible to not have files that are prefixed with an underscore copied across to the assets folder? I thought the `_` before the filename tells Sass not to compile it to CSS...?

**Comment by cshold** [comment]
Good timing, someone just submitted [this update](https://github.com/Shopify/shopify-css-import/pull/15) to fix the same issue. Happy Shopifying.

**Comment by marcobarbosa** [comment]
The update seems to only address `Grunt`. Here is a PR with the `Gulp` fix: https://github.com/Shopify/shopify-css-import/pull/17
